app:
  name: crud-sql
  profile: local
  timeout: 60
  port: 8080

db:
  host: "localhost"
  port: 5433
  username: local_admin
  password: password
  dbName: "crud_sql"
  schema: "crud_sql"
  timezone: "America/Sao_Paulo"
  timeout: 60
  migrationPath: "configs/migrations"
  migrationTable: "bun_migrations"
